/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppLoader: typeof import('./src/components/common/AppLoader.vue')['default']
    AppNavbar: typeof import('./src/components/common/AppNavbar.vue')['default']
    CategoryPinList: typeof import('./src/components/vocabulary/CategoryPinList.vue')['default']
    CongratsStep: typeof import('./src/components/register/CongratsStep.vue')['default']
    GoalStep: typeof import('./src/components/register/GoalStep.vue')['default']
    LanguageSwitcher: typeof import('./src/components/profile/LanguageSwitcher.vue')['default']
    LessonComplete: typeof import('./src/components/lessons/LessonComplete.vue')['default']
    ModuleCard: typeof import('./src/components/common/ModuleCard.vue')['default']
    NameStep: typeof import('./src/components/register/NameStep.vue')['default']
    PhoneStep: typeof import('./src/components/register/PhoneStep.vue')['default']
    ProgressBanner: typeof import('./src/components/home/ProgressBanner.vue')['default']
    PronunciationCard: typeof import('./src/components/vocabulary/PronunciationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanLoading: typeof import('vant/es')['Loading']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
