/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AchievementBadge: typeof import('./src/components/profile/AchievementBadge.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppLoader: typeof import('./src/components/common/AppLoader.vue')['default']
    AppNavbar: typeof import('./src/components/common/AppNavbar.vue')['default']
    CategoryPinList: typeof import('./src/components/vocabulary/CategoryPinList.vue')['default']
    CongratsStep: typeof import('./src/components/register/CongratsStep.vue')['default']
    DailyWord: typeof import('./src/components/home/DailyWord.vue')['default']
    FavoriteWords: typeof import('./src/components/vocabulary/FavoriteWords.vue')['default']
    GoalStep: typeof import('./src/components/register/GoalStep.vue')['default']
    LanguageSwitcher: typeof import('./src/components/profile/LanguageSwitcher.vue')['default']
    LessonCard: typeof import('./src/components/home/LessonCard.vue')['default']
    LessonComplete: typeof import('./src/components/lessons/LessonComplete.vue')['default']
    LessonDetail: typeof import('./src/components/lessons/LessonDetail.vue')['default']
    LessonList: typeof import('./src/components/lessons/LessonList.vue')['default']
    ModuleCard: typeof import('./src/components/common/ModuleCard.vue')['default']
    NameStep: typeof import('./src/components/register/NameStep.vue')['default']
    PhoneStep: typeof import('./src/components/register/PhoneStep.vue')['default']
    ProgressBanner: typeof import('./src/components/home/ProgressBanner.vue')['default']
    PronunciationCard: typeof import('./src/components/vocabulary/PronunciationCard.vue')['default']
    QuizCard: typeof import('./src/components/quiz/QuizCard.vue')['default']
    QuizOptions: typeof import('./src/components/quiz/QuizOptions.vue')['default']
    QuizResult: typeof import('./src/components/quiz/QuizResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/profile/StatsCard.vue')['default']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanLoading: typeof import('vant/es')['Loading']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwitch: typeof import('vant/es')['Switch']
    WordCard: typeof import('./src/components/vocabulary/WordCard.vue')['default']
    WordList: typeof import('./src/components/vocabulary/WordList.vue')['default']
  }
}
